export const  env = {
    BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
    APPWRITE_URL: process.env.NEXT_PUBLIC_APPWRITE_URL,
    APPWRITE_PROJECT_ID: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID,
    APPWRITE_BUCKET_ID: process.env.NEXT_PUBLIC_APPWRITE_BUCKET_ID,
}